In [3]:
import torch.nn as nn
import torch


# 定义模型
class IrisModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(IrisModel, self).__init__()

    def forward(self, x):

        return x

In [10]:
input = [3, 4, 6, 5, 7, 2, 4, 6, 8, 2, 1, 6, 7, 8, 4, 9, 7, 4, 6, 2, 3, 7, 5, 4, 1]
print(input)
input = torch.Tensor(input).view(-1, 5)
print(input)
kernel = [1, 1, 1, 1, 1, 1, 1, 1, 1]
kernel = torch.Tensor(kernel).view(-1, 3)
print(kernel)

[3, 4, 6, 5, 7, 2, 4, 6, 8, 2, 1, 6, 7, 8, 4, 9, 7, 4, 6, 2, 3, 7, 5, 4, 1]
tensor([[3., 4., 6., 5., 7.],
        [2., 4., 6., 8., 2.],
        [1., 6., 7., 8., 4.],
        [9., 7., 4., 6., 2.],
        [3., 7., 5., 4., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [15]:
import torch.nn.functional as F

# The reshaping ensures the input and kernel are in the correct 4D format for conv2d operations in PyTorch, which expects input in the format (batch_size, num_channels, height, width).

input = [3, 4, 6, 5, 7, 2, 4, 6, 8, 2, 1, 6, 7, 8, 4, 9, 7, 4, 6, 2, 3, 7, 5, 4, 1]
input = torch.Tensor(input).view(-1, 5)
input = torch.reshape(input, (1, 1, 5, 5))

print(input)
kernel = [1, 1, 1, 1, 1, 1, 1, 1, 1]
kernel = torch.Tensor(kernel).view(-1, 3)
kernel = torch.reshape(kernel, (1, 1, 3, 3))
print(kernel)

output = F.conv2d(input, kernel, stride=1)
print(output)

output = F.conv2d(input, kernel, stride=1, padding=1)
print(output)

tensor([[[[3., 4., 6., 5., 7.],
          [2., 4., 6., 8., 2.],
          [1., 6., 7., 8., 4.],
          [9., 7., 4., 6., 2.],
          [3., 7., 5., 4., 1.]]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
tensor([[[[39., 54., 53.],
          [46., 56., 47.],
          [49., 54., 41.]]]])
tensor([[[[13., 25., 33., 34., 22.],
          [20., 39., 54., 53., 34.],
          [29., 46., 56., 47., 30.],
          [33., 49., 54., 41., 25.],
          [26., 35., 33., 22., 13.]]]])


In [19]:
import torch
import torchvision
from torch.utils.data import DataLoader

dataset = torchvision.datasets.CIFAR10(
    "../lesson3/dataset",
    train=False,
    transform=torchvision.transforms.ToTensor(),
    download=True,
)

dataloader = DataLoader(dataset, batch_size=64)


class NET(torch.nn.Module):
    def __init__(self):
        super(NET, self).__init__()
        self.conv1 = torch.nn.Conv2d(
            in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=0
        )

    def forward(self, x):
        return self.conv1(x)


model = NET()
print(model)

for data in dataloader:
    inputs, targets = data
    output = model(inputs)
    print(output.shape)

Files already downloaded and verified
NET(
  (conv1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
)
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])


In [29]:
# maxpool
class NET(torch.nn.Module):
    def __init__(self):
        super(NET, self).__init__()
        self.maxpool = torch.nn.MaxPool2d(kernel_size=3)

    def forward(self, x):
        return self.maxpool(x)


model = NET()
print(model)

input = [3, 4, 6, 5, 7, 2, 4, 6, 8, 2, 1, 6, 7, 8, 4, 9, 7, 4, 6, 2, 3, 7, 5, 4, 1]
input = torch.Tensor(input).view(-1, 5)
input = torch.reshape(input, (1, 1, 5, 5))

print(input)
output = model(input)
print(output)

NET(
  (maxpool): MaxPool2d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
)
tensor([[[[3., 4., 6., 5., 7.],
          [2., 4., 6., 8., 2.],
          [1., 6., 7., 8., 4.],
          [9., 7., 4., 6., 2.],
          [3., 7., 5., 4., 1.]]]])
tensor([[[[7.]]]])


In [5]:
import torch


class NET(torch.nn.Module):
    def __init__(self):
        super(NET, self).__init__()
        self.relu1 = torch.nn.ReLU()
        self.sigmoid = torch.nn.Sigmoid()

    def forward(self, x):
        return self.relu1(x)


model = NET()

input = torch.Tensor([-1.0, -3, 0, 1, 2, 3]).view(-1, 1)
print(input)

output = model(input)

print(output)

tensor([[-1.],
        [-3.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 3.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [2.],
        [3.]])


In [9]:
import torch.nn as nn

# With Learnable Parameters
m = nn.BatchNorm2d(100)
# Without Learnable Parameters
m = nn.BatchNorm2d(100, affine=False)
input = torch.randn(20, 100, 35, 45)
print(input)
output = m(input)
print(output)

tensor([[[[ 1.5739e+00, -2.0589e-01,  7.2466e-01,  ...,  2.9014e-01,
            6.5184e-01, -2.2001e-01],
          [-1.1013e+00, -6.8749e-01, -3.2312e-01,  ..., -3.2414e-01,
            1.8466e-02, -6.5425e-01],
          [ 3.6417e-01, -8.3578e-01,  5.9535e-02,  ..., -1.8399e+00,
            4.5769e-01,  1.3409e+00],
          ...,
          [ 1.1181e+00,  3.2106e-01,  1.4553e+00,  ...,  2.1796e+00,
            5.2380e-01,  3.9383e-01],
          [ 1.1394e+00, -5.1542e-01, -2.7357e-01,  ...,  1.3855e+00,
            2.5473e-01,  3.1842e-02],
          [ 1.6649e+00, -9.1433e-01,  2.5700e-01,  ..., -5.9086e-01,
           -9.9666e-01, -1.4361e+00]],

         [[ 1.5018e+00, -8.9892e-01,  9.4672e-01,  ..., -3.5910e-01,
            4.9710e-01, -7.9548e-01],
          [ 1.3975e-01,  1.9148e+00, -1.9607e-01,  ..., -7.5801e-01,
           -1.1011e+00, -5.5306e-02],
          [-2.3881e+00,  2.7177e-01,  5.3047e-01,  ...,  1.3090e+00,
           -1.5670e-01, -6.8142e-01],
          ...,
     

In [10]:
# With Learnable Parameters
m = nn.BatchNorm1d(100)
# Without Learnable Parameters
m = nn.BatchNorm1d(100, affine=False)
input = torch.randn(20, 100)
print(input)
output = m(input)
print(output)

tensor([[ 1.5816, -0.5134,  1.0109,  ..., -0.1547,  0.5954,  1.9128],
        [ 0.7341, -1.8127,  1.8347,  ...,  1.0563,  1.0298,  1.1297],
        [-0.4442,  0.5936,  1.2855,  ..., -1.1007,  2.4239,  0.5625],
        ...,
        [-1.7608,  2.4970,  0.5458,  ...,  0.7444,  0.0277, -0.4119],
        [-0.5247,  0.5788,  0.0605,  ...,  1.2739,  1.0448,  0.7552],
        [-1.6637, -0.6135,  0.5617,  ..., -1.5097, -0.7541,  1.1013]])
tensor([[ 2.3890, -0.6635,  0.5339,  ..., -0.4121,  0.1117,  1.6772],
        [ 1.3717, -1.7775,  1.4025,  ...,  1.2171,  0.5379,  0.7684],
        [-0.0427,  0.2855,  0.8235,  ..., -1.6848,  1.9058,  0.1102],
        ...,
        [-1.6232,  1.9174,  0.0434,  ...,  0.7974, -0.4454, -1.0206],
        [-0.1394,  0.2728, -0.4682,  ...,  1.5099,  0.5527,  0.3338],
        [-1.5067, -0.7494,  0.0602,  ..., -2.2352, -1.2124,  0.7355]])


In [18]:
import torch
import torchvision
from torch.utils.data import DataLoader

dataset = torchvision.datasets.CIFAR10(
    "../lesson3/dataset",
    train=False,
    transform=torchvision.transforms.ToTensor(),
    download=True,
)

dataloader = DataLoader(dataset, batch_size=64, drop_last=True)


class NET(torch.nn.Module):
    def __init__(self):
        super(NET, self).__init__()
        self.l1 = torch.nn.Linear(196608, 10)

    def forward(self, x):
        return self.l1(x)


model = NET()
print(model)

for data in dataloader:
    inputs, targets = data

    # outputs = torch.reshape(inputs, (1, 1, 1, -1))
    outputs = torch.flatten(inputs)
    print(outputs.shape)
    outputs = model(outputs)
    print(outputs.shape)

Files already downloaded and verified
NET(
  (l1): Linear(in_features=196608, out_features=10, bias=True)
)
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608])
torch.Size([10])
torch.Size([196608

In [19]:
import torch
import torchvision
from torch.utils.data import DataLoader

dataset = torchvision.datasets.CIFAR10(
    "../lesson3/dataset",
    train=False,
    transform=torchvision.transforms.ToTensor(),
    download=True,
)

dataloader = DataLoader(dataset, batch_size=64)


class NET(torch.nn.Module):
    def __init__(self):
        super(NET, self).__init__()
        self.conv1 = torch.nn.Conv2d(3, 32, 5, stride=1, padding=2)
        self.maxpool1 = torch.nn.MaxPool2d(2)
        self.conv2 = torch.nn.Conv2d(32, 32, 5, stride=1, padding=2)
        self.maxpool2 = torch.nn.MaxPool2d(2)
        self.conv3 = torch.nn.Conv2d(32, 64, 5, stride=1, padding=2)
        self.maxpool3 = torch.nn.MaxPool2d(2)
        self.flatten = torch.nn.Flatten()
        self.l1 = torch.nn.Linear(1024, 64)
        self.l2 = torch.nn.Linear(64, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = self.maxpool1(x)
        x = self.conv2(x)
        x = self.maxpool2(x)
        x = self.conv3(x)
        x = self.maxpool3(x)
        x = self.flatten(x)
        x = self.l1(x)
        x = self.l2(x)

        return x


model = NET()
print(model)

input = torch.ones((64, 3, 32, 32))
output = model(input)
print(output.shape)
# for data in dataloader:
#     inputs, targets = data
#     output = model(inputs)
#     print(output.shape)

Files already downloaded and verified
NET(
  (conv1): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv3): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (maxpool3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (l1): Linear(in_features=1024, out_features=64, bias=True)
  (l2): Linear(in_features=64, out_features=10, bias=True)
)
torch.Size([64, 10])


In [23]:
import torch
import torchvision
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10(
    "../lesson3/dataset",
    train=False,
    transform=torchvision.transforms.ToTensor(),
    download=True,
)

dataloader = DataLoader(dataset, batch_size=64)


class NET(torch.nn.Module):
    def __init__(self):
        super(NET, self).__init__()
        self.model1 = torch.nn.Sequential(
            torch.nn.Conv2d(3, 32, 5, stride=1, padding=2),
            torch.nn.MaxPool2d(2),
            torch.nn.Conv2d(32, 32, 5, stride=1, padding=2),
            torch.nn.MaxPool2d(2),
            torch.nn.Conv2d(32, 64, 5, stride=1, padding=2),
            torch.nn.MaxPool2d(2),
            torch.nn.Flatten(),
            torch.nn.Linear(1024, 64),
            torch.nn.Linear(64, 10),
        )

    def forward(self, x):
        x = self.model1(x)
        return x


model = NET()
print(model)

input = torch.ones((64, 3, 32, 32))
output = model(input)
print(output.shape)
writer = SummaryWriter("./log_seq")
writer.add_graph(model, input)
writer.close()

Files already downloaded and verified
NET(
  (model1): Sequential(
    (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Flatten(start_dim=1, end_dim=-1)
    (7): Linear(in_features=1024, out_features=64, bias=True)
    (8): Linear(in_features=64, out_features=10, bias=True)
  )
)
torch.Size([64, 10])


In [5]:
import torch

inputs = torch.tensor([1, 2, 3], dtype=torch.float32)
outputs = torch.tensor([1, 2, 5], dtype=torch.float32)

criterion1 = torch.nn.MSELoss(size_average=False)
loss = criterion1(inputs, outputs)
print(loss.item())

criterion1 = torch.nn.L1Loss(size_average=False)
loss = criterion1(inputs, outputs)
print(loss.item())

4.0
2.0


/home/lim/Software/anaconda3/lib/python3.11/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
