In [1]:
import numpy as np
import torch

In [3]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)
t_c, t_u

(tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
          6.0000, 13.0000, 21.0000]),
 tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
         48.4000, 60.4000, 68.4000]))

In [4]:
t_c.shape

torch.Size([11])

In [8]:
def model(x, w, b):
    return w * x + b

In [39]:
def loss_fc(y_predicted, y):
    loss = 0
    for i, data in enumerate(zip(y_predicted, y)):
        # print(i, data[0].item(), data[1].item())
        loss += (data[0] - data[1]) ** 2
    return loss / 11.0

In [43]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c) ** 2
    return squared_diffs.mean()

In [10]:
w = torch.ones(())
b = torch.zeros(())
w, b

(tensor(1.), tensor(0.))

In [12]:
t_p = model(t_u, w, b)
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [44]:
loss = loss_fn(t_p, t_c)
loss

tensor(1763.8848)

In [40]:
loss = loss_fc(t_p, t_c)
loss

tensor(1763.8846)

In [46]:
x = torch.ones(())
y = torch.ones(3, 1)
z = torch.ones(1, 3)
a = torch.ones(2, 1, 1)

print(f"x_shape {x.shape}, y_shape {y.shape}")
print(f"z_shape {z.shape}, y_shape {a.shape}")
print(f"x * a shape :  {(x * a).shape}")
print(f"y * a shape :  {(y * a).shape}")
print(f"z * a shape :  {(z * a).shape}")
print("x * y:", (x * y).shape)
print("y * z:", (y * z).shape)
print("y * z * a:", (y * z * a).shape)

x_shape torch.Size([]), y_shape torch.Size([3, 1])
z_shape torch.Size([1, 3]), y_shape torch.Size([2, 1, 1])
x * a shape :  torch.Size([2, 1, 1])
y * a shape :  torch.Size([2, 3, 1])
z * a shape :  torch.Size([2, 1, 3])
x * y: torch.Size([3, 1])
y * z: torch.Size([3, 3])
y * z * a: torch.Size([2, 3, 3])


Dot production => a[a1, a2,a3], b[b1,b2,b3] \\
a.b = a1*b1 +a2*b2 +a3*b3 \n
Matrix Multiplication MxN \n
A m*p \n
B p\*n \n
C = AB => MxN \n
Broaddcasting Multiplication \n
