In [2]:
a = [1.0, 2.0, 1.0]
a[0]
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [1]:
import torch

a = torch.ones(3)

In [7]:
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [3]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 3.0
points[3] = 1.0
points[4] = 5.0
points[5] = 2.0

points

tensor([4., 1., 3., 1., 5., 2.])

In [4]:
points = torch.tensor([[4.0], [1.0], [3.0], [1.0], [5.0], [2.0]])
points

tensor([[4.],
        [1.],
        [3.],
        [1.],
        [5.],
        [2.]])

In [5]:
points.shape

torch.Size([6, 1])

In [7]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points[0, 1]

tensor(1.)

In [11]:
points[1]

tensor([5., 3.])

In [15]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [16]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [17]:
points.storage()[1]

1.0

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [20]:
points.stride()

(2, 1)

In [22]:
second_point.shape

torch.Size([2])

In [23]:
second_point.size()

torch.Size([2])

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.shape

torch.Size([3, 2])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [32]:
points_t.shape

torch.Size([2, 3])

In [34]:
id(points.storage()) == id(points_t.storage())

True

In [39]:
points.stride()
# points.shape

(2, 1)

In [41]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points_t.stride()

(1, 2)

In [43]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [48]:
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [49]:
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [44]:
transpose_t.shape

torch.Size([5, 4, 3])

In [47]:
some_t.stride()

(20, 5, 1)

In [46]:
transpose_t.stride()

(1, 5, 20)

In [50]:
points.is_contiguous()

True

In [51]:
points_t.is_contiguous()

False

In [52]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [53]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [61]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [55]:
points_t.shape

torch.Size([2, 3])

In [57]:
points_t.stride()

(1, 2)

In [58]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [59]:
points_t_cont.stride()

(3, 1)

In [60]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

.t() only change row and col, not copy data, .contiguous() copy data to a new tensor, stride is skip elements to next elements, .transpose(index1 , index2), .storage() show the data


In [64]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [65]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [66]:
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [67]:
short_points.dtype

torch.int16

In [68]:
double_points.dtype

torch.float64

In [69]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [70]:
double_points.dtype

torch.float64

In [71]:
short_points.dtype

torch.int16

In [72]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [73]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [74]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)

In [75]:
points_64

tensor([0.6284, 0.5803, 0.2731, 0.3736, 0.7709], dtype=torch.float64)

In [76]:
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [77]:
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [82]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[1:]
# points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [83]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [84]:
points[1:, 0]

tensor([5., 2.])

In [85]:
points[None]  # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [87]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [89]:
points = torch.ones([3, 4])
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [91]:
points = torch.ones(3, 4)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [92]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [94]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [96]:
torch.save(points, "./data/outpoint.t")

In [97]:
with open("./data/outpoint.t", "wb") as f:
    torch.save(points, f)

In [98]:
points = torch.load("./data/outpoint.t")

/tmp/ipykernel_33626/2701354899.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load("./data/outpoint.t")


In [99]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
with open("./data/outpoint.t", "rb") as f:
    points = torch.load(f)

/tmp/ipykernel_33626/1663822501.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load(f)


In [103]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 2.0], [3.0, 1.0]], device="cuda")
points_gpu

tensor([[4., 1.],
        [5., 2.],
        [3., 1.]], device='cuda:0')

In [105]:
points_gpu = points.to(device="cuda")
points_gpu

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [106]:
points_gpu = points.to(device="cuda:0")
points_gpu

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [107]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device="cuda")  # <2>
points_gpu

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]], device='cuda:0')

In [108]:
points_gpu = points_gpu + 4
points_gpu

tensor([[8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.]], device='cuda:0')

In [110]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()
points_cpu

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [112]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [113]:
a = torch.ones(3, 2)

In [114]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])