In [2]:
import torch

_ = torch.tensor([0.2126, 0.7152, 0.0722], names=["c"])
_

/tmp/ipykernel_47882/518899274.py:3: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538456841/work/c10/core/TensorImpl.h:1925.)
  _ = torch.tensor([0.2126, 0.7152, 0.0722], names=["c"])


tensor([0.2126, 0.7152, 0.0722], names=('c',))

In [29]:
img_t = torch.randn(3, 5, 5)  # shape[channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights
# img_t.shape

tensor([0.2126, 0.7152, 0.0722])

In [5]:
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[ 0.8451,  0.2919,  0.2824, -1.6726, -1.3670],
          [ 0.6456,  0.0890,  1.2987, -0.2207,  0.2485],
          [ 1.0622,  0.7560, -1.0527,  0.1295, -0.1111],
          [-1.4482,  0.0640,  0.3154, -0.4700, -1.1466],
          [-0.4352,  0.9409, -0.0738, -1.0342, -0.0613]],

         [[ 0.0167, -0.2286, -1.3227, -0.0913,  0.2351],
          [ 0.9751,  0.4635, -0.5464,  1.2534,  0.2755],
          [ 0.1288, -2.5053, -2.0056,  0.2155,  1.9605],
          [-0.0458, -0.8030,  1.6390,  0.0700, -0.7103],
          [ 1.6720,  0.2473,  0.7807, -0.5719,  1.6353]],

         [[ 0.2090, -0.0593, -2.1235, -0.6354,  0.6355],
          [-0.0666,  2.4667, -0.0954,  1.3738,  0.3804],
          [ 0.6903, -0.8842,  0.1841,  0.5826, -0.9782],
          [ 0.1314, -1.4169, -1.5618, -0.0302,  1.0518],
          [-0.9500, -0.3659, -1.9563, -0.1227, -1.9489]]],


        [[[ 0.4660,  0.0056, -0.2504,  0.5091,  0.9817],
          [-0.0349, -1.2229,  0.5041,  0.6071, -0.0502],
          [-0.1452,  0.

-3 represent the 3rd from the last demension, now is channel, usual use this to converted RGB to gray


In [19]:
img_gray_navie = img_t.mean(-3)
img_gray_navie.shape

torch.Size([5, 5])

In [20]:
img_gray_navie

tensor([[-0.1978,  0.0639,  0.0964, -1.0549, -0.7361],
        [ 0.6751,  0.4716,  0.5231, -0.6193, -0.0021],
        [ 0.6630, -0.1405, -0.4087,  0.5052, -0.1133],
        [-0.2274, -0.0105,  0.0940,  0.7019,  0.1376],
        [ 0.2410,  0.4988,  0.5725, -0.0235, -0.2560]])

In [23]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive.shape

torch.Size([2, 5, 5])

In [25]:
unsqueezed_weightd = weights.unsqueeze(-1)
unsqueezed_weightd

tensor([[0.2126],
        [0.7152],
        [0.0722]])

In [26]:
unsqueezed_weightd = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weightd

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [28]:
img_t

tensor([[[ 0.7212,  1.8448,  0.4451,  0.6360, -0.2658],
         [-0.4818,  0.2013,  0.2868, -0.1150,  1.2647],
         [ 0.4788,  0.4130,  0.0868,  1.0954, -0.2706],
         [ 0.7543,  0.6442, -0.7009, -0.7020, -1.0852],
         [ 0.5316, -1.3757,  0.0088,  0.3538, -0.5783]],

        [[-1.2277, -0.2256, -0.2802, -0.5172, -2.3308],
         [-0.5142, -2.1828, -0.8337,  1.3794,  0.1203],
         [-0.0687, -0.3638, -0.6658,  0.7286,  0.1374],
         [ 0.5056,  1.4695,  2.9591,  0.6710,  0.7015],
         [ 0.1561,  0.1887,  0.8208, -1.0239, -1.9043]],

        [[-1.3203,  1.4553,  0.5082,  0.0653,  2.0771],
         [ 1.2853, -1.0630, -1.1397, -0.1577,  2.6100],
         [-0.3586, -0.7229,  0.7332, -1.6746,  0.8347],
         [ 0.8298, -1.7016, -2.0686,  0.1078,  0.7827],
         [ 1.0556, -0.6898,  0.3499,  0.7913,  0.9131]]])

In [27]:
img_weights = img_t * unsqueezed_weightd
img_weights

tensor([[[ 1.5333e-01,  3.9220e-01,  9.4628e-02,  1.3521e-01, -5.6507e-02],
         [-1.0243e-01,  4.2803e-02,  6.0969e-02, -2.4439e-02,  2.6888e-01],
         [ 1.0178e-01,  8.7804e-02,  1.8455e-02,  2.3289e-01, -5.7523e-02],
         [ 1.6037e-01,  1.3696e-01, -1.4901e-01, -1.4924e-01, -2.3072e-01],
         [ 1.1302e-01, -2.9247e-01,  1.8762e-03,  7.5216e-02, -1.2294e-01]],

        [[-8.7807e-01, -1.6135e-01, -2.0042e-01, -3.6987e-01, -1.6670e+00],
         [-3.6774e-01, -1.5611e+00, -5.9626e-01,  9.8656e-01,  8.6041e-02],
         [-4.9145e-02, -2.6020e-01, -4.7617e-01,  5.2107e-01,  9.8294e-02],
         [ 3.6157e-01,  1.0510e+00,  2.1164e+00,  4.7991e-01,  5.0169e-01],
         [ 1.1164e-01,  1.3498e-01,  5.8706e-01, -7.3233e-01, -1.3620e+00]],

        [[-9.5325e-02,  1.0508e-01,  3.6689e-02,  4.7179e-03,  1.4997e-01],
         [ 9.2800e-02, -7.6749e-02, -8.2287e-02, -1.1389e-02,  1.8844e-01],
         [-2.5891e-02, -5.2194e-02,  5.2939e-02, -1.2091e-01,  6.0264e-02],
        

In [30]:
batch_weights = batch_t * unsqueezed_weightd
batch_weights

tensor([[[[ 1.7966e-01,  6.2060e-02,  6.0029e-02, -3.5559e-01, -2.9063e-01],
          [ 1.3726e-01,  1.8922e-02,  2.7610e-01, -4.6930e-02,  5.2832e-02],
          [ 2.2583e-01,  1.6072e-01, -2.2379e-01,  2.7523e-02, -2.3627e-02],
          [-3.0790e-01,  1.3617e-02,  6.7063e-02, -9.9930e-02, -2.4376e-01],
          [-9.2523e-02,  2.0004e-01, -1.5681e-02, -2.1986e-01, -1.3041e-02]],

         [[ 1.1917e-02, -1.6347e-01, -9.4601e-01, -6.5314e-02,  1.6813e-01],
          [ 6.9736e-01,  3.3148e-01, -3.9081e-01,  8.9643e-01,  1.9703e-01],
          [ 9.2153e-02, -1.7918e+00, -1.4344e+00,  1.5411e-01,  1.4021e+00],
          [-3.2763e-02, -5.7428e-01,  1.1722e+00,  5.0038e-02, -5.0798e-01],
          [ 1.1958e+00,  1.7684e-01,  5.5832e-01, -4.0901e-01,  1.1696e+00]],

         [[ 1.5093e-02, -4.2842e-03, -1.5332e-01, -4.5878e-02,  4.5881e-02],
          [-4.8099e-03,  1.7810e-01, -6.8852e-03,  9.9191e-02,  2.7468e-02],
          [ 4.9840e-02, -6.3837e-02,  1.3290e-02,  4.2060e-02, -7.0628e-

In [32]:
img_gray_weighted = img_weights.sum(-3)
img_gray_navie

tensor([[-0.1978,  0.0639,  0.0964, -1.0549, -0.7361],
        [ 0.6751,  0.4716,  0.5231, -0.6193, -0.0021],
        [ 0.6630, -0.1405, -0.4087,  0.5052, -0.1133],
        [-0.2274, -0.0105,  0.0940,  0.7019,  0.1376],
        [ 0.2410,  0.4988,  0.5725, -0.0235, -0.2560]])

In [33]:
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weightd.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [37]:
img_gray_weighted_fancy = torch.einsum("...chw,c->...hw", img_t, weights)
img_gray_weighted_fancy.shape

torch.Size([5, 5])

In [38]:
batch_gray_weighted_fancy = torch.einsum("...chw,c->...hw", batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [39]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [41]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [42]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [43]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [44]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum("channels")
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [45]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))