In [30]:
import numpy as np
import torch

In [31]:
filepath = "../pytorch_dlwpt-code-master/data/p1ch4/bike-sharing-dataset/hour-fixed.csv"
bikes_numpy = np.loadtxt(
    filepath,
    dtype=np.float32,
    delimiter=",",
    skiprows=1,
    converters={1: lambda x: float(x[8:10])},
)
bikes_numpy

array([[1.0000e+00, 1.0000e+00, 1.0000e+00, ..., 3.0000e+00, 1.3000e+01,
        1.6000e+01],
       [2.0000e+00, 1.0000e+00, 1.0000e+00, ..., 8.0000e+00, 3.2000e+01,
        4.0000e+01],
       [3.0000e+00, 1.0000e+00, 1.0000e+00, ..., 5.0000e+00, 2.7000e+01,
        3.2000e+01],
       ...,
       [1.7377e+04, 3.1000e+01, 1.0000e+00, ..., 7.0000e+00, 8.3000e+01,
        9.0000e+01],
       [1.7378e+04, 3.1000e+01, 1.0000e+00, ..., 1.3000e+01, 4.8000e+01,
        6.1000e+01],
       [1.7379e+04, 3.1000e+01, 1.0000e+00, ..., 1.2000e+01, 3.7000e+01,
        4.9000e+01]], dtype=float32)

In [32]:
bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
         1.6000e+01],
        [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
         4.0000e+01],
        [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
         3.2000e+01],
        ...,
        [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
         9.0000e+01],
        [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
         6.1000e+01],
        [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
         4.9000e+01]])

In [33]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [34]:
bikes.shape[1]

17

In [35]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes

tensor([[[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00,
          1.3000e+01, 1.6000e+01],
         [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00,
          3.2000e+01, 4.0000e+01],
         [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00,
          2.7000e+01, 3.2000e+01],
         ...,
         [2.2000e+01, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00,
          3.1000e+01, 3.4000e+01],
         [2.3000e+01, 1.0000e+00, 1.0000e+00,  ..., 1.1000e+01,
          1.7000e+01, 2.8000e+01],
         [2.4000e+01, 1.0000e+00, 1.0000e+00,  ..., 1.5000e+01,
          2.4000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.0000e+00, 1.0000e+00,  ..., 4.0000e+00,
          1.3000e+01, 1.7000e+01],
         [2.6000e+01, 2.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.6000e+01, 1.7000e+01],
         [2.7000e+01, 2.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          8.0000e+00, 9.0000e+00],
         ...,
         [4.5000e+01, 2.0000e+00, 1.0000e+00,  ..., 1.1000e+01,
          2.000

The goal of this code is to reshape the bikes tensor into a new 3D tensor where:

The first dimension corresponds to the number of days (calculated automatically).
The second dimension is 24, representing 24 hours per day.
The third dimension is the number of columns/features (e.g., data like the number of bikes sold or temperature).


In [36]:
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [37]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes.shape, daily_bikes.stride()
daily_bikes

tensor([[[1.0000e+00, 2.0000e+00, 3.0000e+00,  ..., 2.2000e+01,
          2.3000e+01, 2.4000e+01],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         ...,
         [3.0000e+00, 8.0000e+00, 5.0000e+00,  ..., 3.0000e+00,
          1.1000e+01, 1.5000e+01],
         [1.3000e+01, 3.2000e+01, 2.7000e+01,  ..., 3.1000e+01,
          1.7000e+01, 2.4000e+01],
         [1.6000e+01, 4.0000e+01, 3.2000e+01,  ..., 3.4000e+01,
          2.8000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.6000e+01, 2.7000e+01,  ..., 4.5000e+01,
          4.6000e+01, 4.7000e+01],
         [2.0000e+00, 2.0000e+00, 2.0000e+00,  ..., 2.0000e+00,
          2.0000e+00, 2.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         ...,
         [4.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.1000e+01,
          0.000

In [38]:
first_day = bikes[:24].long()
whether_onehot = torch.zeros(first_day.shape[0], 4)
first_day[:, 9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [39]:
first_day = bikes[:24].long()
first_day

tensor([[  1,   1,   1,   0,   1,   0,   0,   6,   0,   1,   0,   0,   0,   0,
           3,  13,  16],
        [  2,   1,   1,   0,   1,   1,   0,   6,   0,   1,   0,   0,   0,   0,
           8,  32,  40],
        [  3,   1,   1,   0,   1,   2,   0,   6,   0,   1,   0,   0,   0,   0,
           5,  27,  32],
        [  4,   1,   1,   0,   1,   3,   0,   6,   0,   1,   0,   0,   0,   0,
           3,  10,  13],
        [  5,   1,   1,   0,   1,   4,   0,   6,   0,   1,   0,   0,   0,   0,
           0,   1,   1],
        [  6,   1,   1,   0,   1,   5,   0,   6,   0,   2,   0,   0,   0,   0,
           0,   1,   1],
        [  7,   1,   1,   0,   1,   6,   0,   6,   0,   1,   0,   0,   0,   0,
           2,   0,   2],
        [  8,   1,   1,   0,   1,   7,   0,   6,   0,   1,   0,   0,   0,   0,
           1,   2,   3],
        [  9,   1,   1,   0,   1,   8,   0,   6,   0,   1,   0,   0,   0,   0,
           1,   7,   8],
        [ 10,   1,   1,   0,   1,   9,   0,   6,   0,   1,   0, 

In [40]:
whether_onehot = torch.zeros(first_day.shape[0], 4)
whether_onehot.shape

torch.Size([24, 4])

In [41]:
whether_onehot.scatter_(dim=1, index=first_day[:, 9].unsqueeze(1).long() - 1, value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [42]:
torch.cat((bikes[:24], whether_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [43]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4, daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [44]:
daily_weather_onehot.scatter_(1, daily_bikes[:, 9, :].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [45]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)

In [46]:
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0

In [47]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = (daily_bikes[:, 10, :] - temp_min) / (temp_max - temp_min)

In [48]:
temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = (daily_bikes[:, 10, :] - torch.mean(temp)) / torch.std(temp)